### ISSUE TITLE
Full Code

### ISSUE THREAD

**Issue by avijit9** [zlai0/CorrFlow#1]
Hi,

When will the full code be released?

**Comment by zlai0** [comment]
Hi, Thanks for your interest! We will release the code in a month.

**Comment by RaphaelRoyerRivard** [comment]
I'm also eager to test it!

**Comment by RaphaelRoyerRivard** [comment]
Any update?

**Comment by tshrjn** [comment]
Hi there, any plans to release the code?

**Comment by zlai0** [comment]
Hi all, thanks for the interest. We have released the code. Enjoy!
