### ISSUE TITLE
Color quantization

### ISSUE THREAD

**Issue by ananyahjha93** [zlai0/CorrFlow#3]
The OxUvA dataset also loads centroids from centroids_16k_kinetics_10000samples.npy for quantizing the color space. Shouldn't the code compute new centroids for a different dataset? Can we use the same centroids for a custom dataset that we plan to use with the code?

**Comment by WeidiXie** [comment]
@ananyahjha93 Ideally, it should be recomputed. 
Our OxUvA results are preliminary. Also, I would imagine, loading from centroids normally won't be too harmful, because Kinetics is pretty large and diverse.

**Comment by tshrjn** [comment]
Would it be possible to put up the script for how the centroids were created?

**Comment by priyasundaresan** [comment]
Here is an implementation for finding the centroids: https://lmcaraig.com/color-quantization-using-k-means
